spring.datasource.max-active: 10
spring.datasource.initial-size: 5
spring.datasource.max-idle: 5
spring.datasource.min-idle: 1
spring.datasource.test-while-idle: true
spring.datasource.test-on-borrow: true
spring.datasource.validation-query: SELECT 1
spring.datasource.time-between-eviction-runs-millis: 5000
spring.datasource.min-evictable-idle-time-millis: 60000
spring.jpa.show-sql: true
spring.datasource.driverClassName: org.postgresql.Driver
spring.jpa.database.driverClassName: org.postgresql.Driver

spring:
  application:
     name: accounts-service
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: accounts
    password: accounts
  jpa:
    database: POSTGRESQL
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: POSTGRESQL
     hibernate:
        ddl-auto: create

security:
  basic:
    enabled: false
